jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node-10:
          node_version: ^10.10.0
    steps:
      - template: scripts/azure-run-tests.yml
  - job: macOS
    pool:
      vmImage: "macOS 10.13"
    strategy:
      matrix:
        node-10:
          node_version: ^10.10.0
    steps:
      - template: scripts/azure-run-tests.yml